---
  root: true
  parser: babel-eslint
  extends:
    - airbnb
    - plugin:flowtype/recommended
  plugins:
    - flowtype
  rules:
    semi:
      - error
      - never
    no-underscore-dangle: off

    react/jsx-filename-extension: off
    react/jsx-wrap-multilines:
      - error
      - declaration: true
        assignment: true
        return: true
        arrow: false
    react/sort-comp:
      - error
      - order:
          - static-methods
          - lifecycle
          - render
          - everything-else

    flowtype/delimiter-dangle:
      - error
      - always-multiline
    flowtype/semi:
      - error
      - never