---
  root: true
  parser: babel-eslint
  extends:
    - airbnb
    - plugin:flowtype/recommended
  plugins:
    - flowtype
  rules:
    semi:
      - error
      - never
    react/jsx-filename-extension: off
    react/jsx-wrap-multilines:
      - error
      - declaration: true
        assignment: true
        return: true
        arrow: false